### ISSUE TITLE
OSX Support?

### ISSUE THREAD

**Issue by trevorprater** [cryptax/fittools#1]
Traceback (most recent call last):
  File "trackerlock.py", line 371, in <module>
    dongleReset()
  File "trackerlock.py", line 213, in dongleReset
    response = device.read(0x82, 32, timeout)
  File "/Library/Python/2.7/site-packages/usb/core.py", line 905, in read
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/Library/Python/2.7/site-packages/usb/core.py", line 190, in setup_request
    self.managed_claim_interface(device, intf)
  File "/Library/Python/2.7/site-packages/usb/core.py", line 146, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/Library/Python/2.7/site-packages/usb/backend/libusb1.py", line 747, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/Library/Python/2.7/site-packages/usb/backend/libusb1.py", line 552, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)

**Comment by freewil** [comment]
> usb.core.USBError: [Errno 13] Access denied (insufficient permissions)

does it need root to access the USB?

**Comment by cryptax** [comment]
@freewil: No, you don't need to be root, but then under Linux, you'll need to add a line in /etc/udev/rules.d/99-fitbit.rules:

```
 SUBSYSTEM=="usb", ATTR{idVendor}=="2687", ATTR{idProduct}=="fb01", OWNER="yourusername", GROUP="plugdev", SYMLINK+="fitbit", MODE="0666"
```
